version: '3.1'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME : root
  SPRING_DATASOURCE_PASSWORD: root
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123

    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - ./data/grafana:/var/lib/grafana

#  springboot-essentials:
#
#    image: registry.hub.docker.com/marconefreitas/springboot-essentials:0.0.1-SNAPSHOT
#    ports:
     environment:
       <<: *database-variables
#    - "8080:8080"


volumes:
  devdojo_data: